version: '3.4'

services:
  rabbitmq:
     image: rabbitmq:3-management
     container_name: rabbitmq
     ports:
      - "5672:5672"       
      - "15672:15672"     
     environment:
      - RABBITMQ_DEFAULT_USER=sa
      - RABBITMQ_DEFAULT_PASS=sa
     volumes:
      - ./.container/queue/data/:/var/lib/rabbitmq
      - ./.container/queue/log/:/var/log/rabbitmq

  fashionflows.statemachine.orchestration:
    image: ${DOCKER_REGISTRY-}fashionflowsstatemachineorchestration
    build:
      context: .
      dockerfile: FashionFlows.StateMachine/FashionFlows.StateMachine.Orchestration/Dockerfile


  fashionflows.product.api:
    image: ${DOCKER_REGISTRY-}fashionflowsproductapi
    build:
      context: .
      dockerfile: FashionFlows.Services/Products/FashionFlows.Product.Api/Dockerfile


  fashionflows.order.api:
    image: ${DOCKER_REGISTRY-}fashionflowsorderapi
    build:
      context: .
      dockerfile: FashionFlows.Services/Order/FashionFlows.Order.Api/Dockerfile


  fashionflows.payment.api:
    image: ${DOCKER_REGISTRY-}fashionflowspaymentapi
    build:
      context: .
      dockerfile: FashionFlows.Services/Payment/FashionFlows.Payment.Api/FashionFlows.Payment.Api/Dockerfile

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "4317:4317"
      - "4318:4318"
      - "16686:16686"

volumes:
  loki-data:
  grafana-storage:
